# -*- coding: utf-8 -*-
"""Untitled5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ECdprKgz5mmTfNvMRtNl7rKkiJSJvnwD
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report, confusion_matrix, roc_curve, roc_auc_score

df = pd.read_csv("data.csv")

# clean column names
df.columns = df.columns.str.strip()

print("Shape:", df.shape)
df.head()

cols = {c.lower(): c for c in df.columns}

plt.figure()
df['Bankrupt?'].value_counts().plot(kind='bar')
plt.title("Distribution of Bankrupt vs Non-Bankrupt Companies")
plt.show()

profit_cols = [
    cols['roa(a) before interest and % after tax'],
    cols['net income to total assets'],
    cols["net income to stockholder's equity"]
]

for col in profit_cols:
    plt.figure()
    plt.boxplot([df[df['Bankrupt?']==0][col],
                 df[df['Bankrupt?']==1][col]])
    plt.xticks([1,2], ['Non-Bankrupt','Bankrupt'])
    plt.title(f'Profitability: {col}')
    plt.show()

liquidity_cols = [
    cols['current ratio'],
    cols['quick ratio'],
    cols['working capital to total assets'],
    cols['cash/total assets']
]

for col in liquidity_cols:
    plt.figure()
    plt.boxplot([df[df['Bankrupt?']==0][col],
                 df[df['Bankrupt?']==1][col]])
    plt.xticks([1,2], ['Non-Bankrupt','Bankrupt'])
    plt.title(f'Liquidity: {col}')
    plt.show()

debt_cols = [
    cols['debt ratio %'],
    cols['borrowing dependency'],
    cols['liability to equity'],
    cols['equity to liability']
]

for col in debt_cols:
    plt.figure()
    plt.boxplot([df[df['Bankrupt?']==0][col],
                 df[df['Bankrupt?']==1][col]])
    plt.xticks([1,2], ['Non-Bankrupt','Bankrupt'])
    plt.title(f'Leverage: {col}')
    plt.show()

corr = df.corr()

top20 = corr['Bankrupt?'].abs().sort_values(ascending=False).head(21).index

plt.figure(figsize=(12,10))
plt.imshow(df[top20].corr())
plt.colorbar()
plt.title("Correlation Heatmap of Top Bankruptcy Indicators")
plt.show()

X = df.drop('Bankrupt?', axis=1)
y = df['Bankrupt?']

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y
)

scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

model = RandomForestClassifier(
    n_estimators=300,
    random_state=42,
    class_weight='balanced'
)

model.fit(X_train, y_train)

y_pred = model.predict(X_test)
y_prob = model.predict_proba(X_test)[:,1]

print(classification_report(y_test, y_pred))

importances = pd.Series(model.feature_importances_, index=X.columns)
top_features = importances.sort_values(ascending=False).head(10)

plt.figure()
top_features.sort_values().plot(kind='barh')
plt.title("Top 10 Financial Indicators Predicting Bankruptcy")
plt.show()

print("Top Predictors:")
print(top_features)

cm = confusion_matrix(y_test, y_pred)

plt.figure()
plt.imshow(cm)
plt.title("Confusion Matrix")
plt.xlabel("Predicted")
plt.ylabel("Actual")
plt.show()

fpr, tpr, _ = roc_curve(y_test, y_prob)
auc = roc_auc_score(y_test, y_prob)

plt.figure()
plt.plot(fpr, tpr)
plt.plot([0,1],[0,1],'--')
plt.title(f"ROC Curve (AUC = {auc:.2f})")
plt.show()







